# Schema for the configuration files of the attachinline module.

attachinline.settings:
  type: config_object
  label: 'Attach Inline Settings'
  mapping:
    csp-allow-method:
      type: string
      label: 'CSP Allow Method'
